### ISSUE TITLE
Linux builds failing

### ISSUE THREAD

**Issue by jjhelmus** [conda-forge/arm_pyart-feedstock#1]
The linux-64 builds are currently [failing](https://circleci.com/gh/conda-forge/arm_pyart-feedstock/1) with the following

```
File "/opt/conda/envs/_test/lib/python2.7/site-packages/matplotlib/backends/qt_compat.py", line 124, in <module>
    from PyQt4 import QtCore, QtGui
ImportError: libXext.so.6: cannot open shared object file: No such file or directory
```

I think libXext.so.6 is expected to be provided by the system not conda. The [manylinux PEP 0513](https://www.python.org/dev/peps/pep-0513/) includes libXext.so.6 in the list of allowed libraries.  

I can add `sudo yum install libXext` to the run_docker_build.sh file but it might be better to include this directly in the Docker image.

**Comment by pelson** [comment]
> I can add sudo yum install libXext to the run_docker_build.sh file but it might be better to include this directly in the Docker image.

Agreed. 

The image is from https://github.com/conda-forge/arm_pyart-feedstock/blob/master/ci_support/run_docker_build.sh#L30. That is controlled (currently), from https://github.com/pelson/Obvious-CI/blob/master/obvious-ci.docker/linux64_obvci/Dockerfile.

**Comment by jjhelmus** [comment]
Addressed in PR #2

**Comment by ocefpaf** [comment]
> I can add sudo yum install libXext to the run_docker_build.sh file but it might be better to include this directly in the Docker image.

@pelson and @jjhelmus I am having second thoughts about adding these to the Docker image. If we leave them in the `run_docker_build.sh` (or even the `buils.sh`) we have a self documenting recipe when it comes to system libs. I am getting many reports of broken packages when people try to use IOOS binaries with minimalistic Docker images.

By not adding these to the Docker image we not only get the system libraries documentation for free, but we also avoid possible build problems. For example, someone adds `jpeg` lib to the docker image and my recipe, that I want to compile against `jasper`, ends up picking that `jpeg` lib instead.

Of course there are many ways to avoid these issues, but maybe keeping a simpler Docker image for the builds will save us some debug time.

What do you think?

**Comment by jjhelmus** [comment]
I would be in favor of NOT including these libraries in the Docker image and in instead having them installed using yum in either `run_docker_build.sh` or `build.sh` for the reasons outlined by @ocefpaf.  

I also think that the `yum install -y libXent libXrender libSM tk libX11-devel` line in this repositories `run_docker_build.sh` file should be removed so Docker image is configures in the same manner in the feedstock as in the staged-recipe.  This would mean that the install logic for these libraries would need to be included in the `build.sh` file of the recipe.

**Comment by jjhelmus** [comment]
Just discovered that the [auditwheel](https://github.com/pypa/auditwheel) tool my be used to examine conda packages to see if the meet the "manylinux1" standard.  This might be helpful to find packages which are accidentally linked to system libraries.

```
$ auditwheel show linux-64-tensorflow-0.7.1-py35_1.tar.bz2

linux-64-tensorflow-0.7.1-py35_1.tar.bz2 is consistent with the
following platform tag: "linux_x86_64".

The wheel references the following external versioned symbols in
system-provided shared libraries: GLIBC_2.14, CXXABI_1.3.5, GCC_3.0,
GLIBCXX_3.4.19.

This constrains the platform tag to "linux_x86_64". In order to
achieve a more compatible tag, you would to recompile a new wheel from
source on a system with earlier versions of these libraries, such as
CentOS 5.

The following external shared libraries are required by the wheel:
{
    "libc.so.6": "/lib64/libc-2.5.so",
    "libdl.so.2": "/lib64/libdl-2.5.so",
    "libgcc_s.so.1": "/lib64/libgcc_s-4.1.2-20080825.so.1",
    "libm.so.6": "/lib64/libm-2.5.so",
    "libpthread.so.0": "/lib64/libpthread-2.5.so",
    "libstdc++.so.6": "/usr/lib64/libstdc++.so.6.0.8",
    "libz.so.1": "/lib64/libz.so.1.2.3"
}

In order to achieve the tag platform tag "manylinux1_x86_64" the
following shared library dependencies will need to be eliminated:

libz.so.1
```

**Comment by ocefpaf** [comment]
Cool!

PS: do you know about `conda inspect linkages <package_name>`? That is not as verbose nor provides all the functionalities from `auditwheel`, but works on Linux and OS X.

**Comment by jjhelmus** [comment]
That is helpful, looks like the package must be installed though.

**Comment by jakirkham** [comment]
Added this issue ( https://github.com/conda-forge/conda-forge.github.io/issues/82 ) to include `yum` requirements as part of the recipe itself. We can then use these to ensure they are installed correctly without having to hack them in to autogenerated files.

**Comment by pelson** [comment]
Actually, this one is solved with the docker updates we did a few weeks back. CircleCI is green 👍
