### ISSUE TITLE
BINSTAR_TOKEN needs to be updated on AppVeyor?

### ISSUE THREAD

**Issue by jjhelmus** [conda-forge/arm_pyart-feedstock#7]
The latest Windows builds are not [uploading](https://ci.appveyor.com/project/conda-forge/arm-pyart-feedstock/build/1.0.6/job/dbylyiiupj0l3go6), I think this is due to an invalid BINSTAR_TOKEN.  @ocefpaf or @pelson can you have a look and advise?

**Comment by jjhelmus** [comment]
Looks like PR #4 remove the BINSTAR_TOKEN variable from appveyor.yml.

**Comment by ocefpaf** [comment]
`conda smithy rerender` should fix that. I guess that conda smithy is choking on `[win and py35 and np==19]`

**Comment by jjhelmus** [comment]
As we are no long building for NumPy 1.9 can that line be removed?

**Comment by ocefpaf** [comment]
Not sure if that line is the culprit... trying to figure out what is wrong with conda-smithy. Can you try re-rendering it locally and see if you can reproduce the problem?

**Comment by jjhelmus** [comment]
Where do I get the circle and Appveyor tokens?  conda smithy rerender mentioned that I need them

```
~/dev/conda-forge/arm_pyart-feedstock$ conda smithy rerender
No circle token. Put one in ~/.conda-smithy/circle.token
No appveyor token. Put one in ~/.conda-smithy/appveyor.token
Using Anaconda Cloud api site https://api.anaconda.org
...
```

**Comment by jjhelmus** [comment]
FYI (to myself more than anyone else), the `skip: True # [win and py35 and np==19]` line was added because the default channel is missing a Python 3.5, NumPy 1.9 netcdf4 package for Windows and so the build would fail during the test phase.

**Comment by jjhelmus** [comment]
But the re-render does work other than missing those tokens:

```
~/dev/conda-forge/arm_pyart-feedstock$ conda smithy rerender
No circle token. Put one in ~/.conda-smithy/circle.token
No appveyor token. Put one in ~/.conda-smithy/appveyor.token
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ..
Fetching package metadata: ..
Fetching package metadata: ..

CI support files regenerated. These need to be pushed to github!
$ conda list conda-smithy
# packages in environment at /home/jhelmus/anaconda:
#
conda-smithy              0.8.4                    py35_0    conda-forge
```

**Comment by ocefpaf** [comment]
You don't need the tokens to rerender (or lint a recipe).

> FYI (to myself more than anyone else), the `skip: True # [win and py35 and np==19]` line was added because the default channel is missing a Python 3.5, NumPy 1.9 netcdf4 package for Windows and so the build would fail during the test phase.

``` shell
> conda search netcdf4 | grep np19py35
Using Anaconda Cloud api site https://api.anaconda.org
                             1.1.9                np19py35_0  defaults        
                             1.2.1                np19py35_1  conda-forge     
                             1.2.1                np19py35_2  conda-forge     
                             1.2.2                np19py35_0  conda-forge     
                             1.2.3                np19py35_0  conda-forge     
                             1.2.3.1              np19py35_0  conda-forge     
                             1.2.3.1              np19py35_1  conda-forge
```

**Comment by ocefpaf** [comment]
@pelson I cannot understand why the TOKEN is being removed.
@jjhelmus we can re-add it manually:

``` yaml
  CONDA_PY: "27"
  BINSTAR_TOKEN:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    secure: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC

  matrix:
```

But we need to figure why `conda smithy rerender` is failing there.

**Comment by pelson** [comment]
I can't quite remember why, but I have it added in https://github.com/conda-forge/arm_pyart-feedstock/pull/3.

It may have been that there was an extra process run (such as `conda smithy register-ci`) which goes away and registers everything that isn't registered, and encrypts everything that needs encrypting. To do that, you _do_ need the tokens that smithy is warning about.

Advice: Take the commit from #3, and re-render on top of that - you should find the AppVeyor token is set appropriately.
