### ISSUE TITLE
Is the pandas <2 pin still required?

### ISSUE THREAD

**Issue by akrherz** [conda-forge/arm_pyart-feedstock#83]
### Comment:

I see pandas < 2 was pinned down a month ago.  Is this still a valid requirement for 1.15.1 ?

**Comment by zssherman** [comment]
@akrherz I remember we originally pinned it due to a datetime datatype issue. I'll do some testing and see if we can do a microrelease to remove it, if the problem has resolved.

**Comment by zssherman** [comment]
@akrherz The pinning has been removed in the latest release, cheers! Closing this.
